-- MySQL Script generated by MySQL Workbench
-- Fri May 31 19:57:53 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vet_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vet_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vet_db` DEFAULT CHARACTER SET utf8 ;
USE `vet_db` ;

-- -----------------------------------------------------
-- Table `vet_db`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(100) NOT NULL,
  `address` VARCHAR(75) NOT NULL,
  `phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vet_db`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Workers` (
  `id_worker` INT NOT NULL AUTO_INCREMENT,
  `specialization` VARCHAR(50) NOT NULL,
  `fullname` VARCHAR(50) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_worker`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vet_db`.`Species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Species` (
  `id_species` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_species`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vet_db`.`Breeds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Breeds` (
  `id_breeds` INT NOT NULL AUTO_INCREMENT,
  `id_species` INT NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_breeds`),
  INDEX `SpeciesBreedsFK_idx` (`id_species` ASC) VISIBLE,
  CONSTRAINT `SpeciesBreedsFK`
    FOREIGN KEY (`id_species`)
    REFERENCES `vet_db`.`Species` (`id_species`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vet_db`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `id_species` INT NOT NULL,
  `id_breed` INT NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `date_birth` DATE NOT NULL,
  PRIMARY KEY (`id_animal`),
  INDEX `ClientAnimalFK_idx` (`id_client` ASC) VISIBLE,
  INDEX `SpeciesAnimalFK_idx` (`id_species` ASC) VISIBLE,
  INDEX `BreedaAnimalFK_idx` (`id_breed` ASC) VISIBLE,
  CONSTRAINT `ClientAnimalFK`
    FOREIGN KEY (`id_client`)
    REFERENCES `vet_db`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SpeciesAnimalFK`
    FOREIGN KEY (`id_species`)
    REFERENCES `vet_db`.`Species` (`id_species`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `BreedaAnimalFK`
    FOREIGN KEY (`id_breed`)
    REFERENCES `vet_db`.`Breeds` (`id_breeds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vet_db`.`Visit_Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Visit_Log` (
  `id_visit` INT NOT NULL AUTO_INCREMENT,
  `id_client` INT NOT NULL,
  `id_animal` INT NOT NULL,
  `id_worker` INT NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `symptoms` TEXT NOT NULL,
  PRIMARY KEY (`id_visit`),
  INDEX `ClientVisitFK_idx` (`id_client` ASC) VISIBLE,
  INDEX `AnimalVisitFK_idx` (`id_animal` ASC) VISIBLE,
  INDEX `WorkersVisitFK_idx` (`id_worker` ASC) VISIBLE,
  CONSTRAINT `ClientVisitFK`
    FOREIGN KEY (`id_client`)
    REFERENCES `vet_db`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AnimalVisitFK`
    FOREIGN KEY (`id_animal`)
    REFERENCES `vet_db`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `WorkersVisitFK`
    FOREIGN KEY (`id_worker`)
    REFERENCES `vet_db`.`Workers` (`id_worker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vet_db`.`Medical_Record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vet_db`.`Medical_Record` (
  `id_medrec` INT NOT NULL AUTO_INCREMENT,
  `id_animal` INT NOT NULL,
  `id_worker` INT NOT NULL,
  `date` DATE NOT NULL,
  `description` TEXT NOT NULL,
  `diagnosis` TEXT NOT NULL,
  `recommendations` TEXT NOT NULL,
  PRIMARY KEY (`id_medrec`),
  INDEX `AnimalRecordFK_idx` (`id_animal` ASC) VISIBLE,
  INDEX `WorkersMedRecFK_idx` (`id_worker` ASC) VISIBLE,
  CONSTRAINT `AnimalRecordFK`
    FOREIGN KEY (`id_animal`)
    REFERENCES `vet_db`.`Animal` (`id_animal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `WorkersMedRecFK`
    FOREIGN KEY (`id_worker`)
    REFERENCES `vet_db`.`Workers` (`id_worker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
